### ISSUE TITLE
Cannot install chkrootkit

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#53] opened 2015-11-17 16:36 UTC
##### Summary
System: Slackware64-current, slpkg v3.0.1

While trying to install chkrootkit using the sbo repository, it fails with an error.

##### Output

```bash
# slpkg -s sbo chkrootkit
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  chkrootkit              0.50               x86_64         SBo

Installing summary
===============================================================================
Total 1 package.
1 package will be installed, 0 already installed and 0 package                                                                                                                                  
will be upgraded.                                                                                                                                                                               

Would you like to continue [y/N]? y

[1/2][ Download ] --> chkrootkit.tar.gz

--2015-11-17 09:34:19--  http://slackbuilds.org/slackbuilds/14.1/system/chkrootkit.tar.gz
Resolving slackbuilds.org (slackbuilds.org)... 208.94.238.115
Connecting to slackbuilds.org (slackbuilds.org)|208.94.238.115|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2876 (2.8K) [application/x-gzip]
Saving to: '/tmp/slpkg/build/chkrootkit.tar.gz'

chkrootkit.tar.gz                               100%[=========================================================================================================>]   2.81K  --.-KB/s   in 0s     

2015-11-17 09:34:19 (545 MB/s) - '/tmp/slpkg/build/chkrootkit.tar.gz' saved [2876/2876]


[2/2][ Download ] --> chkrootkit.tar.gz

--2015-11-17 09:34:19--  ftp://ftp.pangeia.com.br/pub/seg/pac/chkrootkit.tar.gz
           => '/tmp/slpkg/build/.listing'
Resolving ftp.pangeia.com.br (ftp.pangeia.com.br)... 187.33.4.179
Connecting to ftp.pangeia.com.br (ftp.pangeia.com.br)|187.33.4.179|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/seg/pac ... done.
==> PASV ... done.    ==> LIST ... done.

.listing                                            [ <=>                                                                                                      ]   5.23K  --.-KB/s   in 0.003s 

2015-11-17 09:34:22 (1.83 MB/s) - '/tmp/slpkg/build/.listing' saved [5355]

Removed '/tmp/slpkg/build/.listing'.
--2015-11-17 09:34:22--  ftp://ftp.pangeia.com.br/pub/seg/pac/chkrootkit.tar.gz
           => '/tmp/slpkg/build/chkrootkit.tar.gz'
==> CWD not required.
==> SIZE chkrootkit.tar.gz ... 38616
==> PASV ... done.    ==> REST 2876 ... done.    
==> RETR chkrootkit.tar.gz ... done.
Length: 38616 (38K), 35740 (35K) remaining (unauthoritative)

chkrootkit.tar.gz                               100%[+++++++==================================================================================================>]  37.71K  45.0KB/s   in 0.8s   

2015-11-17 09:34:24 (45.0 KB/s) - '/tmp/slpkg/build/chkrootkit.tar.gz' saved [38616]


Traceback (most recent call last):
  File "/usr/bin/slpkg", line 41, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 759, in main
    arguments[args[0]]()
  File "/usr/lib64/python2.7/site-packages/slpkg/main.py", line 346, in pkg_install
    SBoInstall(self.args[2:], flag).start(if_upgrade=False)
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 148, in start
    self.continue_to_install()
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 180, in continue_to_install
    installs, upgraded = self.build_install()
  File "/usr/lib64/python2.7/site-packages/slpkg/sbo/slackbuild.py", line 332, in build_install
    auto=False).build()
  File "/usr/lib64/python2.7/site-packages/slpkg/pkg/build.py", line 81, in build
    check_md5(self.sbo_md5[src], src)
  File "/usr/lib64/python2.7/site-packages/slpkg/checksum.py", line 35, in check_md5
    md5s = md5(src_file)
  File "/usr/lib64/python2.7/site-packages/slpkg/md5sum.py", line 31, in md5
    with open(source) as file_to_check:
IOError: [Errno 2] No such file or directory: 'chkrootkit.tar.gz'
```

**Comment by dslackw** [comment] 2015-11-19 01:12
Hmm same source name, I do not know if this is slpkg problem.

**Comment by BrentonEarl** [comment] 2015-11-19 01:21
The developer of chkrootkit released the source for download at this url:  ftp://ftp.pangeia.com.br/pub/seg/pac/chkrootkit.tar.gz

The maintainer for the SlackBuild has it extracting with this command:
```bash
tar xvf $CWD/$PRGNAM.tar.gz
```
You might need to add some logic to slpkg to look for source with:
```bash
tar xvf $PRGNAM-$VERSION.tar.gz || tar xvf $VERSION.tar.gz || tar xvf $PRGNAM.tar.gz
```

The tarball extracts to directory $PRGNAM-$VERSION/, so chkrootkit-0.5/.  There is no way around this unless the SlackBuild maintainer renames the tarball appropriately prior to extracting it.

**Comment by dslackw** [comment] 2015-11-19 02:06
The problem is that source and SlackBuild downloaded in the same directory with the same name, in which this replaces the first.

**Comment by dslackw** [comment] 2015-12-30 07:22
Fixed in develop branch as usual.

**Comment by BrentonEarl** [comment] 2015-12-30 08:59
Thanks!

**Closed** 2015-12-30 08:59 UTC
